import type { Metadata } from "next";
import "@/app/globals.css";

import UploadButton from "@/app/(main)/components/UploadButton"
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "clonebnb",
  description: "Generated by create next app",
};
export default function hostAdmin({children} : Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en">
            <body>    
                <div className="flex">
                    <Sidebar className=""></Sidebar>
                    {children}
                </div>
            </body>
        </html>
        // <UploadButton></UploadButton>
    )
}